# Generated by Django 4.1.2 on 2022-10-25 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='大カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='MinorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='小カテゴリ名')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textbook.majorcategory', verbose_name='大カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='textbook/thubnail', verbose_name='サムネイル画像')),
                ('content', models.CharField(max_length=2000, verbose_name='内容')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='textbook.minorcategory', verbose_name='小カテゴリ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
