# Generated by Django 4.1.2 on 2022-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcategory',
            name='order',
            field=models.IntegerField(verbose_name='順番'),
        ),
    ]
