# Generated by Django 4.1.2 on 2022-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='content',
        ),
        migrations.AddField(
            model_name='textbook',
            name='movie_content',
            field=models.FileField(blank=True, null=True, upload_to='textbook/movie/', verbose_name='動画'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='text_content',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='textbook/thubnail/', verbose_name='サムネイル画像'),
        ),
    ]
