# Generated by Django 4.1.2 on 2022-10-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_rename_movie_content_textbook_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='text_content',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='textbook/movie/', verbose_name='ファイル'),
        ),
    ]
