# Generated by Django 4.1.2 on 2022-12-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0003_textbook_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='explanation',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='説明文'),
        ),
    ]
