# Generated by Django 4.1.2 on 2022-10-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0004_remove_textbook_text_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='category',
            new_name='minor_category',
        ),
    ]
