# Generated by Django 4.1.2 on 2022-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbook', '0005_textbook_top_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtubeのサムネイル'),
        ),
    ]
