# Generated by Django 4.1.2 on 2022-11-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='c_active',
            field=models.BooleanField(default=True, verbose_name='Cさんのステータス'),
        ),
    ]
