# Generated by Django 4.1.2 on 2022-11-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_ac_c_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ac_active',
            field=models.BooleanField(default=True, verbose_name='ACのステータス'),
        ),
    ]
