# Generated by Django 4.1.2 on 2022-11-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_question_ac_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='c_active',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ac_active',
        ),
    ]
