# Generated by Django 4.1.2 on 2022-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_ac_c_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='c_is_active',
            new_name='c_is_ac_active',
        ),
        migrations.AddField(
            model_name='abc',
            name='c_is_abc_active',
            field=models.BooleanField(default=True, verbose_name='Cさんの状態'),
        ),
        migrations.AddField(
            model_name='interview',
            name='c_is_interview_active',
            field=models.BooleanField(default=True, verbose_name='Cさんの状態'),
        ),
        migrations.AddField(
            model_name='question',
            name='c_is_question_active',
            field=models.BooleanField(default=True, verbose_name='Cさんの状態'),
        ),
    ]
