# Generated by Django 4.1.2 on 2022-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_c_is_active_ac_c_is_ac_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abc',
            name='c_is_abc_active',
            field=models.BooleanField(default=True, verbose_name='ABCステータス'),
        ),
        migrations.AlterField(
            model_name='ac',
            name='c_is_ac_active',
            field=models.BooleanField(default=True, verbose_name='ACステータス'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='c_is_interview_active',
            field=models.BooleanField(default=True, verbose_name='面談ステータス'),
        ),
        migrations.AlterField(
            model_name='question',
            name='c_is_question_active',
            field=models.BooleanField(default=True, verbose_name='質問ステータス'),
        ),
    ]
